-- view_work.sql

-- 1. 기본테이블 생성
CREATE TABLE DEPT_COPY
AS
SELECT * FROM DEPT;

CREATE TABLE EMP_COPY
AS
SELECT * FROM EMP;

-- 2. 뷰 생성 : 서브쿼리 이용
CREATE VIEW EMP_VIEW30
AS
SELECT EMPNO, ENAME, DEPTNO
FROM EMP_COPY
WHERE DEPTNO = 30;


SELECT * FROM EMP_VIEW30;

-- 데이터 사전 뷰
SELECT * FROM USER_TABLES;  -- 전체 테이블 목록
SELECT * FROM USER_VIEWS;  -- 전체 뷰 목록

-- 뷰 이용 레코드 삽입
INSERT INTO EMP_VIEW30
VALUES(1111, 'aaaa', 30)

SELECT * FROM EMP_VIEW30;  --  뷰
SELECT * FROM EMP_COPY;  -- 기본테이블

-- 3. 뷰 삭제
DROP VIEW EMP_VIEW30;

--  4. 뷰 사용 목적
/*
 *   1) 복잡하고 긴 쿼리문 간단히 사용
 *   2) 보안 목적
 */


CREATE OR REPLACE VIEW JOIN_VIEW
AS
(SELECT E.EMPNO, E.ENAME, D.DNAME, D.LOC
	FROM DEPT_TAB D, EMP_TAB E
	WHERE D.DEPTNO = E.DEPTNO AND D.LOC LIKE '대%')
WITH READ ONLY;  -- 읽기 전용 VIEW 

-- 2) 보안목적
-- 영업사원 제공 view
CREATE VIEW SALES_VIEW
AS
(SELECT EMPNO, ENAME, COMM FROM EMP WHERE JOB = 'SALESMAN')
WITH READ ONLY;

