-- DML_work.sql

/*
 * INSERT/UPDATE/DELEDTE : commint 대상
 * SELECT : commit 대상 아님  --> DB 변화 없기 때문
 *  - 기본 쿼리 이용 DML 실습
 *  - 서브 쿼리 이용 DML 실습
 */

-- TABLE 생성
CREATE TABLE DEPT01(
DEPTNO NUMBER(4),
DNAME VARCHAR2(30),
LOC VARCHAR2(20)
);


-- 1. 레코드 삽입
INSERT INTO DEPT01 (DEPTNO, DNAME, LOC)
VALUES(10, 'ACCOUNTING', 'NEW YORK');

INSERT INTO DEPT01 
VALUES (20, 'RESEARCH', 'DALLAS');  -- 컬럼명 생략


-- <문제1> EMP 테이블의 4개 칼럼의 구조를 이용하여 SAM01 테이블을 생성하시오.
CREATE TABLE SAM01
AS
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE 1=0;

-- <문제2> SAM01 테이블에 다음과 같은 데이터를 추가하시오.
INSERT INTO SAM01 VALUES (1000, 'APPLE', 'POLICE', 10000);
INSERT INTO SAM01 VALUES (1010, 'BANANA', 'NURSE', 15000);
INSERT INTO SAM01 VALUES (1020, 'ORANGE', 'DOCTOR', 25000);

-- 암시적 NULL 삽입
INSERT INTO DEPT01 (DEPTNO, DNAME) VALUES (30, 'SALES');  -- loc NULL 삽입

-- 명시적 NULL 삽입
INSERT INTO DEPT01 VALUES (40, 'OPERATIONS', NULL);

SELECT * FROM DEPT01;

-- <문제3> SAM01 테이블의 JOB 칼럼이 NULL 값을 갖는 2개의 행을 추가하시오.
INSERT INTO SAM01 VALUES (1030, 'VERY', NULL , 25000);
INSERT INTO SAM01(EMPNO, ENAME, SAL) VALUES (1040, 'CAT',  2000);

DROP TABLE DEPT01 purge;
DROP TABLE DEPT02;

CREATE TABLE DEPT02  -- main
AS 
SELECT * FROM DEPT WHERE 1=0;  -- sub

-- 서브쿼리를 이용한 레코드 삽입  --> AS 없음
INSERT INTO DEPT02  -- main 
SELECT * FROM DEPT;  -- sub

--<문제4>SAM01 테이블에 서브 쿼리문을 사용하여 EMP 에 저장된 사원 중 10번 부서 소속 사원의 정보를 추가하시오.
INSERT INTO SAM01  -- main 
SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE DEPTNO = 10; 

-- 2. 다중 테이블 레코드 삽입
 
--		1) 테이블 생성
CREATE TABLE EMP_HIR
AS
SELECT empno, ename, hiredate FROM emp WHERE 1 = 0;

CREATE TABLE EMP_MGR
AS
SELECT empno, ename, mgr  FROM emp WHERE 1 = 0;

--		2)
INSERT ALL 
INTO EMP_HIR VALUES(EMPNO, ENAME, HIREDATE)
INTO EMP_MGR VALUES(EMPNO, ENAME, MGR)
SELECT EMPNO, ENAME, HIREDATE, MGR 
FROM EMP
WHERE DEPTNO=20;


-- 3. UPDATE

-- 전체 테이블 대상 
CREATE TABLE EMP01 AS SELECT * FROM EMP;

UPDATE EMP01 SET DEPTNO=30; -- 전체 변경
UPDATE EMP01 SET SAL =  SAL *1.1; 
UPDATE EMP01 SET HIREDATE =  SYSDATE; 

-- 특정 행 대상
UPDATE EMP01 SET DEPTNO=10 WHERE DEPTNO = 30;
UPDATE EMP01 SET SAL = SAL*1.1 WHERE SAL >= 3000;

-- <문제5> 
UPDATE SAM01 SET SAL = SAL-5000 WHERE SAL >= 10000;


--2개 이상 컬럼 수정
UPDATE EMP01 SET DEPTNO = 20, JOB =  'MANSGER' WHERE ENAME = 'SCOTT';

-- 서브쿼리를 이용한 데이터 수정하기
UPDATE DEPT01
SET LOC = (SELECT LOC FROM DEPT01 WHERE DEPTNO = 10)
WHERE DEPTNO=20;

-- <문제6>
CREATE TABLE SAM02
AS
SELECT ENAME, SAL, HIREDATE, DEPTNO FROM EMP

-- <문제7>DALLAS 에 위치한 부서 소속 사원들의 급여를 1000 인상하시오.
UPDATE SAM02
SET SAL = SAL + 1000
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'DALLAS');

-- 서브쿼리를 이용한 2개의 컬럼 수정
UPDATE DEPT01
SET (DNAME, LOC)=(SELECT DNAME, LOC FROM DEPT01 WHERE DEPTNO=10)
WHERE DEPTNO=50;


-- 4. DELETE 
DELETE FROM DEPT01
WHERE DEPT = 30;  --> WHERE절이 없으면 모든 행 삭제


-- < 실습9 > SAM01 테이블에서 직책이 정해지지 않은 사원을 삭제하시오.
DELETE FROM SAM01 WHERE JOB IS NULL;

-- 서브 쿼리를 이용한 레코드 삭제
DELETE FROM EMP01
WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES')



